development: &development
  adapter: postgresql
  database: curriculums_proy_development
  username: root
  password: root 
  pool: 5
  timeout: 5000

test:
  <<: *development
  database: curriculums_proy_test

production: &production
  adapter: postgresql
  database: curriculums_proy_production
  pool: 5
  timeout: 5000

staging:
  <<: *production
  database: curriculums_proy_staging

integration:
  <<: *production
  database: curriculums_proy_integration
